ALTER TABLE legacy_raw_prices ALTER COLUMN fetched_at SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE raw_insider ALTER COLUMN fetched_at SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE raw_congressional ALTER COLUMN fetched_at SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE raw_macro ALTER COLUMN fetched_at SET DATA TYPE TIMESTAMPTZ;
