name: test

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.11"
          enable-cache: true
      - run: uv sync --locked
      - run: uv run pytest -q -o addopts=''
